SELECT T.SUPPLIER
      ,T.QUOTE_DATE
      ,SUM(T.COST) COST
      ,T.BRACKET_PRICING
      ,T.TUBE_ASSEMBLY_ID
      ,EXTRACT(YEAR FROM T.QUOTE_DATE) AS QUOTE_YEAR
      ,EXTRACT(MONTH FROM T.QUOTE_DATE) AS QUOTE_MONTH
FROM DATASET.TB_PRICE_QUOTE T
GROUP BY T.SUPPLIER
        ,T.QUOTE_DATE
        ,T.BRACKET_PRICING
        ,T.TUBE_ASSEMBLY_ID        
        ,T.QUANTITY,QUOTE_YEAR,QUOTE_MONTH