WITH TB_COMPONENT AS (
SELECT CASE WHEN TRIM(TYPE                    ) = 'NA' THEN 'NAO_CADASTRADO' ELSE UPPER(TYPE             )  END AS TYPE
			,CASE WHEN TRIM(GROOVE            ) = 'NA' THEN 'NAO_CADASTRADO' ELSE UPPER(GROOVE           )  END AS GROOVE
			,CASE WHEN TRIM(BASE_TYPE         ) = 'NA' THEN 'NAO_CADASTRADO' ELSE UPPER(BASE_TYPE        )  END AS BASE_TYPE
			,CASE WHEN TRIM(ORIENTATION       ) = 'NA' THEN 'NAO_CADASTRADO' ELSE UPPER(ORIENTATION      )  END AS ORIENTATION
			,CASE WHEN TRIM(COMPONENT_ID      ) = 'NA' THEN 'NAO_CADASTRADO' ELSE UPPER(COMPONENT_ID     )  END AS COMPONENT_ID
			,CASE WHEN TRIM(OUTSIDE_SHAPE     ) = 'NA' THEN 'NAO_CADASTRADO' ELSE UPPER(OUTSIDE_SHAPE    )  END AS OUTSIDE_SHAPE
			,CASE WHEN TRIM(UNIQUE_FEATURE    ) = 'NA' THEN 'NAO_CADASTRADO' ELSE UPPER(UNIQUE_FEATURE   )  END AS UNIQUE_FEATURE
			,CASE WHEN TRIM(COMPONENT_TYPE_ID ) = 'NA' THEN 'NAO_CADASTRADO' ELSE UPPER(COMPONENT_TYPE_ID)  END AS COMPONENT_TYPE_ID
            ,ROUND(CAST(CASE WHEN TRIM(WEIGHT           ) = 'NA' THEN '0' ELSE WEIGHT            END AS NUMERIC),2) AS WEIGHT
			,ROUND(CAST(CASE WHEN TRIM(BASE_DIAMETER    ) = 'NA' THEN '0' ELSE BASE_DIAMETER     END AS NUMERIC),2) AS BASE_DIAMETER
			,ROUND(CAST(CASE WHEN TRIM(HEIGHT_OVER_TUBE ) = 'NA' THEN '0' ELSE HEIGHT_OVER_TUBE  END AS NUMERIC),2) AS HEIGHT_OVER_TUBE
			,ROUND(CAST(CASE WHEN TRIM(BOLT_PATTERN_LONG) = 'NA' THEN '0' ELSE BOLT_PATTERN_LONG END AS NUMERIC),2) AS BOLT_PATTERN_LONG
			,ROUND(CAST(CASE WHEN TRIM(BOLT_PATTERN_WIDE) = 'NA' THEN '0' ELSE BOLT_PATTERN_WIDE END AS NUMERIC),2) AS BOLT_PATTERN_WIDE
			,ROUND(CAST(CASE WHEN TRIM(SHOULDER_DIAMETER) = 'NA' THEN '0' ELSE SHOULDER_DIAMETER END AS NUMERIC),2) AS SHOULDER_DIAMETER      
			,CASE WHEN TRIM(CONNECTION_TYPE_ID) = 'NA' OR TRIM(CONNECTION_TYPE_ID) = '9999'THEN 'NAO_CADASTRADO' ELSE UPPER(CONNECTION_TYPE_ID) END AS CONNECTION_TYPE_ID
FROM SANDBOX_MIS.COMPONENT_BOSS)
SELECT COMPONENT_ID
			,COMPONENT_TYPE_ID
			,TYPE
			,CONNECTION_TYPE_ID
			,OUTSIDE_SHAPE
			,BASE_TYPE
			,HEIGHT_OVER_TUBE
			,BOLT_PATTERN_LONG
			,BOLT_PATTERN_WIDE
			,GROOVE
			,BASE_DIAMETER
			,SHOULDER_DIAMETER
			,UNIQUE_FEATURE
			,ORIENTATION
			,WEIGHT
FROM TB_COMPONENT