WITH TB_PRICE_QUOTE AS (
SELECT CAST(QUOTE_DATE AS DATE) QUOTE_DATE
			,ROUND(CAST(CASE WHEN TRIM(COST)  = 'NA' THEN '0' ELSE COST END AS NUMERIC),2) AS COST		
			,CASE WHEN TRIM(SUPPLIER        ) = 'NA' THEN 'NAO_CADASTRADO' ELSE UPPER(SUPPLIER        ) END AS SUPPLIER
			,CASE WHEN TRIM(BRACKET_PRICING ) = 'NA' THEN 'NAO_CADASTRADO' ELSE UPPER(BRACKET_PRICING ) END AS BRACKET_PRICING
			,CASE WHEN TRIM(TUBE_ASSEMBLY_ID) = 'NA' THEN 'NAO_CADASTRADO' ELSE UPPER(TUBE_ASSEMBLY_ID) END AS TUBE_ASSEMBLY_ID
			,CAST(CASE WHEN TRIM(QUANTITY          ) = 'NA' THEN '0' ELSE QUANTITY           END AS NUMERIC) AS QUANTITY
			,CAST(CASE WHEN TRIM(ANNUAL_USAGE      ) = 'NA' THEN '0' ELSE ANNUAL_USAGE       END AS NUMERIC) AS ANNUAL_USAGE
			,CAST(CASE WHEN TRIM(MIN_ORDER_QUANTITY) = 'NA' THEN '0' ELSE MIN_ORDER_QUANTITY END AS NUMERIC) AS MIN_ORDER_QUANTITY
FROM SANDBOX_MIS.PRICE_QUOTE )
SELECT  TUBE_ASSEMBLY_ID	
		,SUPPLIER
		,QUOTE_DATE
		,ANNUAL_USAGE
		,MIN_ORDER_QUANTITY
		,BRACKET_PRICING
		,QUANTITY
		,COST
FROM TB_PRICE_QUOTE