SELECT TUBE_ASSEMBLY_ID
      ,CAST(CASE WHEN TRIM(QUANTITY_1) = 'NA' THEN '0' ELSE QUANTITY_1 END AS NUMERIC) AS QUANTITY_1
      ,CAST(CASE WHEN TRIM(QUANTITY_2) = 'NA' THEN '0' ELSE QUANTITY_2 END AS NUMERIC) AS QUANTITY_2
      ,CAST(CASE WHEN TRIM(QUANTITY_3) = 'NA' THEN '0' ELSE QUANTITY_3 END AS NUMERIC) AS QUANTITY_3
      ,CAST(CASE WHEN TRIM(QUANTITY_4) = 'NA' THEN '0' ELSE QUANTITY_4 END AS NUMERIC) AS QUANTITY_4
      ,CAST(CASE WHEN TRIM(QUANTITY_5) = 'NA' THEN '0' ELSE QUANTITY_5 END AS NUMERIC) AS QUANTITY_5
      ,CAST(CASE WHEN TRIM(QUANTITY_6) = 'NA' THEN '0' ELSE QUANTITY_6 END AS NUMERIC) AS QUANTITY_6
      ,CAST(CASE WHEN TRIM(QUANTITY_7) = 'NA' THEN '0' ELSE QUANTITY_7 END AS NUMERIC) AS QUANTITY_7
      ,CAST(CASE WHEN TRIM(QUANTITY_8) = 'NA' THEN '0' ELSE QUANTITY_8 END AS NUMERIC) AS QUANTITY_8
      ,CASE WHEN TRIM(COMPONENT_ID_1)  = 'NA' OR TRIM(COMPONENT_ID_1) = '9999' THEN 'NAO_CADASTRADO' ELSE UPPER(COMPONENT_ID_1) END AS COMPONENT_ID_1
      ,CASE WHEN TRIM(COMPONENT_ID_2)  = 'NA' OR TRIM(COMPONENT_ID_2) = '9999' THEN 'NAO_CADASTRADO' ELSE UPPER(COMPONENT_ID_2) END AS COMPONENT_ID_2
      ,CASE WHEN TRIM(COMPONENT_ID_3)  = 'NA' OR TRIM(COMPONENT_ID_3) = '9999' THEN 'NAO_CADASTRADO' ELSE UPPER(COMPONENT_ID_3) END AS COMPONENT_ID_3
      ,CASE WHEN TRIM(COMPONENT_ID_4)  = 'NA' OR TRIM(COMPONENT_ID_4) = '9999' THEN 'NAO_CADASTRADO' ELSE UPPER(COMPONENT_ID_4) END AS COMPONENT_ID_4
      ,CASE WHEN TRIM(COMPONENT_ID_5)  = 'NA' OR TRIM(COMPONENT_ID_5) = '9999' THEN 'NAO_CADASTRADO' ELSE UPPER(COMPONENT_ID_5) END AS COMPONENT_ID_5
      ,CASE WHEN TRIM(COMPONENT_ID_6)  = 'NA' OR TRIM(COMPONENT_ID_6) = '9999' THEN 'NAO_CADASTRADO' ELSE UPPER(COMPONENT_ID_6) END AS COMPONENT_ID_6
      ,CASE WHEN TRIM(COMPONENT_ID_7)  = 'NA' OR TRIM(COMPONENT_ID_7) = '9999' THEN 'NAO_CADASTRADO' ELSE UPPER(COMPONENT_ID_7) END AS COMPONENT_ID_7
      ,CASE WHEN TRIM(COMPONENT_ID_8)  = 'NA' OR TRIM(COMPONENT_ID_8) = '9999' THEN 'NAO_CADASTRADO' ELSE UPPER(COMPONENT_ID_8) END AS COMPONENT_ID_8
FROM SANDBOX_MIS.BILL_MATERIAL